config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create] # :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w(chinese italian japanese french belgian).sort
  validates :name, :address, :phone_number, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
  @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # GET /restaurants/1
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show"
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-lg">
        <img src="http://localhost:3000/assets/location-b50966a9a3b401c4e3267ce4679d574415066a53ea9a2059ef7d1cc71e417ae8.png" title="Restaurant list" >

<!--         <%= link_to restaurants_path, class: "navbar-brand" do %>
          <%= image_tag "location.png" %>
          <% end %> -->

        <div id="navbarSupportedContent">

          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to restaurants_path, class: "nav-link" do %>
              <%= image_tag "list.png", title: "All restaurants" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_restaurant_path, class: "nav-link" do %>
              <%= image_tag "new.png", title: "Add a restaurant" %>
              <% end %>
            </li>
          </ul>

        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.sort.each do |restaurant| %>
<div class="restaurant-card">
      <span class="item">
      <%= restaurant.name %>
      </span>
      <span>
      <%= link_to "Show", restaurant_path(restaurant) %>
      </span>
  </div>
<% end %>

app/views/restaurants/new.html.erb
  <h1>Add a restaurant</h1>
  <div class="restaurant-new">
    <%= simple_form_for (@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <div id="button-create-back">
      <%= f.submit class: 'btn btn-primary mt-2' %>
      <%= link_to "Back to list", restaurants_path %>
    </div>
    <% end %>
  </div>

app/views/restaurants/show.html.erb
<div>
  <h1><%= @restaurant.name %></h1>
  <div class="restaurant-details">
    Category: <%= @restaurant.category %><br>
    Address: <%= @restaurant.address %><br>
    Phone: <%= @restaurant.phone_number %>
  </div>

  <ul class="list-group mb-3">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item ">
      <span class="badge badge-primary badge-pill mr-2">
        <%= review.rating %><br>
      </span>
      <%= review.content %>
      </li>
    <% end %>
  </ul>

  <h1>Leave a review</h1>
  <div class="review-new">
    <%= simple_form_for [ @restaurant, @review ] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: 0..5 %>
      <div id="button-create-back">
        <%= f.submit "Submit review", class: "btn btn-primary mt-2" %>
        <%= link_to "Back to list", restaurants_path %>
      </div>
    <% end %>
  </div>

</div>

app/views/reviews/new.html.erb
<h1>Leave a review</h1>
<div class="review-new">
  <%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 0..5 %>
    <div id="button-create-back">
      <%= f.submit "Submit review", class: "btn btn-primary mt-2" %>
      <%= link_to "Back to list", restaurants_path %>
    </div>
  <% end %>
</div>